# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
PHP-btce-api/ fd465a0
Updated Readme
￼marinu666 committed over 2 years ago
1 changed file
32 additions and 0 deletions
README.md
README.md
@@ -2,3 +2,35 @@ btce
 ====
 
 BTC-e API Class
+
+
+Allows for the use of the Private and Public APIs from BTC-e.
+
+Built in Support For:
+       Public API:
+               Currency Pair Fees
+               Currency Pair Tickers
+               Currency Pair Trades
+               Currency Pair Depths
+               
+       Private API:
+               Trade (Buy/Sell) Orders
+               Checking on Past Orders
+               API Query Method
+                       - Auto-recovery from bad noonces
+                       - Allows any method with any parameters to be called on btc-e
+                       
+                       
+       Example Usage provided in Example.php
+       
+       
+       How to integrate:
+       require_once('btce-api.php');
+       $BTCeAPI = new BTCeAPI({APIKEY},{APISECRET}[,Optional:{START_NOONCE}]);
+       
+       
+       Private API Quick Example:
+       $BTCeAPI->makeOrder($amount, $pair, $direction, $price);
+       
+       Public API Quick Example:
+       $BTCeAPI->getPairDepth('btc_usd');
0 comments on commit fd465a0
Comment on fd465a0
￼
￼Comment
￼ Desktop version
