version: 2

jobs:

  lint:
    working_directory: /work
    docker: [{image: 'dnephin/docker-circleci-task-runner:17.05'}]
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker version
      - run:
          name: "Lint"
          command: |
            ./tasks lint

  cross:
    working_directory: /work
    docker: [{image: 'dnephin/docker-circleci-task-runner:17.05'}]
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Cross"
          command: |
            CID_FILENAME=.cid ./tasks cross
            docker cp $(cat .cid):/go/src/github.com/docker/cli/build /work/build

      - store_artifacts:
          path: /work/build

  test:
    working_directory: /work
    docker: [{image: 'dnephin/docker-circleci-task-runner:17.05'}]
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Unit Test with Coverage"
          command: |
            CID_FILENAME=.cid ./tasks test-coverage

      - run:
          name: "Upload to Codecov"
          command: |
            docker cp $(cat .cid):/go/src/github.com/docker/cli/coverage.txt coverage.txt
            curl -s https://codecov.io/bash | bash

  validate:
    working_directory: /work
    docker: [{image: 'dnephin/docker-circleci-task-runner:17.05'}]
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Validate Vendor, Docs, and Code Generation"
          command: |
            rm -f .dockerignore # include .git
            ./tasks vendor compose-jsonschema manpages yamldocs

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - cross
      - test
      - validate
