//go:build linux

package standalone

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// writeEtcFiles generates the /etc/hostname, /etc/hosts and /etc/resolv.conf
// files that are bind-mounted into the container. They are written at
// creation time with placeholder network information and rewritten at start
// once the container's address is known.
func (e *engine) writeEtcFiles(dir string, m *containerMeta) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	hostname := m.Config.Hostname
	if err := os.WriteFile(filepath.Join(dir, "hostname"), []byte(hostname+"\n"), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "hosts"), []byte(e.hostsContent(m)), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "resolv.conf"), []byte(e.resolvConfContent(m)), 0o644)
}

func (*engine) hostsContent(m *containerMeta) string {
	var b strings.Builder
	b.WriteString("127.0.0.1\tlocalhost\n")
	b.WriteString("::1\tlocalhost ip6-localhost ip6-loopback\n")
	b.WriteString("fe00::\tip6-localnet\n")
	b.WriteString("ff00::\tip6-mcastprefix\n")
	b.WriteString("ff02::1\tip6-allnodes\n")
	b.WriteString("ff02::2\tip6-allrouters\n")

	hostGateway := hostGatewayIP(m)
	for _, eh := range m.HostConfig.ExtraHosts {
		name, ip, ok := strings.Cut(eh, ":")
		if !ok {
			continue
		}
		if ip == "host-gateway" {
			ip = hostGateway
		}
		if ip == "" {
			continue
		}
		fmt.Fprintf(&b, "%s\t%s\n", ip, strings.ReplaceAll(name, ";", " "))
	}
	if hostGateway != "" {
		fmt.Fprintf(&b, "%s\thost.docker.internal host.containers.internal\n", hostGateway)
	}
	names := m.Config.Hostname
	if m.Name != "" && m.Name != names {
		names += " " + m.Name
	}
	switch {
	case m.Network.Backend == networkHost:
		// Nothing: the host's own hostname resolution applies.
	case m.Network.IPAddress != "":
		fmt.Fprintf(&b, "%s\t%s\n", m.Network.IPAddress, names)
	default:
		fmt.Fprintf(&b, "127.0.0.1\t%s\n", names)
	}
	return b.String()
}

// hostGatewayIP returns the address through which the container can reach
// the host, when known.
func hostGatewayIP(m *containerMeta) string {
	switch m.Network.Backend {
	case networkPasta:
		if pastaFeatures().mapGuestAddr {
			return pastaMapGuestAddr
		}
		return ""
	case networkSlirp:
		return "10.0.2.2"
	case networkBridge:
		if m.Network.Gateway != "" {
			return m.Network.Gateway
		}
		return cniGateway
	case networkHost:
		return "127.0.0.1"
	}
	return ""
}

func (*engine) resolvConfContent(m *containerMeta) string {
	var nameservers, search, options []string
	for _, d := range m.HostConfig.DNS {
		nameservers = append(nameservers, d.String())
	}
	search = m.HostConfig.DNSSearch
	options = m.HostConfig.DNSOptions

	hostNS, hostSearch, hostOpts := hostResolvConf()
	if len(nameservers) == 0 {
		switch m.Network.Backend {
		case networkHost:
			nameservers = hostNS
		default:
			nameservers = append(nameservers, m.Network.DNS...)
			for _, ns := range hostNS {
				if !isLoopbackAddr(ns) {
					nameservers = append(nameservers, ns)
				}
			}
		}
		if len(nameservers) == 0 {
			nameservers = []string{"8.8.8.8", "8.8.4.4"}
		}
	}
	if len(search) == 0 {
		search = hostSearch
	}
	if len(options) == 0 {
		options = hostOpts
	}

	var b strings.Builder
	b.WriteString("# Generated by docker (standalone mode)\n")
	if len(search) > 0 && (len(search) != 1 || search[0] != ".") {
		b.WriteString("search " + strings.Join(search, " ") + "\n")
	}
	for _, ns := range nameservers {
		b.WriteString("nameserver " + ns + "\n")
	}
	if len(options) > 0 {
		b.WriteString("options " + strings.Join(options, " ") + "\n")
	}
	return b.String()
}
