//go:build linux

package standalone

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/containerd/containerd/v2/contrib/seccomp"
	"github.com/containerd/containerd/v2/core/containers"
	"github.com/containerd/containerd/v2/core/content"
	"github.com/containerd/containerd/v2/pkg/oci"
	cerrdefs "github.com/containerd/errdefs"
	"github.com/containerd/platforms"
	"github.com/moby/moby/api/types/container"
	ocispec "github.com/opencontainers/image-spec/specs-go/v1"
	specs "github.com/opencontainers/runtime-spec/specs-go"
)

// ociImage adapts a resolved image to the oci.Image interface used by
// oci.WithImageConfig.
type ociImage struct {
	ri *resolvedImage
	cs content.Store
}

func (i ociImage) Config(context.Context) (ocispec.Descriptor, error) { return i.ri.configDesc, nil }
func (i ociImage) ContentStore() content.Store                        { return i.cs }

// specInput carries everything needed to build the OCI runtime spec.
type specInput struct {
	id      string
	meta    *containerMeta
	image   *resolvedImage
	mounts  []specs.Mount
	etcDir  string // directory holding hostname/hosts/resolv.conf
	netMode string // resolved network backend
}

// buildSpec translates the Docker container configuration into an OCI
// runtime spec using containerd's spec generator.
func (e *engine) buildSpec(ctx context.Context, s *session, c *containers.Container, in specInput) (*oci.Spec, error) {
	cfg := in.meta.Config
	hc := in.meta.HostConfig

	entrypoint := cfg.Entrypoint
	cmd := cfg.Cmd
	if len(entrypoint) == 0 {
		entrypoint = in.image.config.Config.Entrypoint
		if len(cmd) == 0 {
			cmd = in.image.config.Config.Cmd
		}
	}
	args := append(append([]string{}, entrypoint...), cmd...)
	if len(args) == 0 {
		return nil, fmt.Errorf("no command specified: %w", cerrdefs.ErrInvalidArgument)
	}
	in.meta.Path = args[0]
	in.meta.Args = args[1:]

	opts := []oci.SpecOpts{
		oci.WithDefaultUnixDevices,
		oci.WithImageConfig(ociImage{ri: in.image, cs: s.content()}),
		oci.WithProcessArgs(args...),
		oci.WithEnv(cfg.Env),
		oci.WithHostname(cfg.Hostname),
		oci.WithAnnotations(hc.Annotations),
		oci.WithAnnotations(map[string]string{"io.docker.standalone.name": in.meta.Name}),
	}
	if cfg.Domainname != "" {
		opts = append(opts, oci.WithDomainname(cfg.Domainname))
	}
	if cfg.WorkingDir != "" {
		opts = append(opts, oci.WithProcessCwd(cfg.WorkingDir))
	}
	if cfg.User != "" {
		opts = append(opts, oci.WithUser(cfg.User))
	}
	if len(hc.GroupAdd) > 0 {
		opts = append(opts, oci.WithAppendAdditionalGroups(hc.GroupAdd...))
	}
	if cfg.Tty {
		opts = append(opts, oci.WithTTY)
	}
	if hc.Umask != nil {
		opts = append(opts, oci.WithUmask(*hc.Umask))
	}

	// /etc/hostname, /etc/hosts and /etc/resolv.conf are generated by the
	// engine and bind-mounted into the container, like Docker does.
	etcMounts := []specs.Mount{
		{Destination: "/etc/hostname", Type: "bind", Source: filepath.Join(in.etcDir, "hostname"), Options: []string{"rbind", "rprivate", "rw"}},
		{Destination: "/etc/hosts", Type: "bind", Source: filepath.Join(in.etcDir, "hosts"), Options: []string{"rbind", "rprivate", "rw"}},
		{Destination: "/etc/resolv.conf", Type: "bind", Source: filepath.Join(in.etcDir, "resolv.conf"), Options: []string{"rbind", "rprivate", "rw"}},
	}
	// containerd's default spec does not mount the cgroup filesystem;
	// Docker does, so that containers can see their own limits.
	cgroupMount := []specs.Mount{{
		Destination: "/sys/fs/cgroup",
		Type:        "cgroup",
		Source:      "cgroup",
		Options:     []string{"ro", "nosuid", "noexec", "nodev"},
	}}
	opts = append(opts, oci.WithMounts(cgroupMount), oci.WithMounts(etcMounts), oci.WithMounts(in.mounts))

	shm := hc.ShmSize
	if shm <= 0 {
		shm = 64 * 1024 * 1024
	}
	if !hc.IpcMode.IsHost() {
		opts = append(opts, oci.WithDevShmSize(shm/1024))
	}

	opts = append(opts, e.namespaceOpts(in)...)

	secOpts, err := securityOpts(e.cfg, hc)
	if err != nil {
		return nil, err
	}
	opts = append(opts, secOpts...)
	opts = append(opts, resourceOpts(hc)...)

	platform := in.meta.Platform
	if platform == "" {
		platform = platforms.DefaultString()
	}
	spec, err := oci.GenerateSpecWithPlatform(ctx, s, platform, c, opts...)
	if err != nil {
		return nil, fmt.Errorf("generating OCI spec: %w", err)
	}
	return spec, nil
}

// namespaceOpts returns the spec options selecting the container's
// namespaces and cgroup placement.
func (e *engine) namespaceOpts(in specInput) []oci.SpecOpts {
	hc := in.meta.HostConfig
	var opts []oci.SpecOpts
	switch {
	case hc.NetworkMode.IsHost() || in.netMode == networkHost:
		opts = append(opts, oci.WithHostNamespace(specs.NetworkNamespace))
		if e.cfg.rootless {
			// Mounting a fresh sysfs is only permitted with a network
			// namespace owned by the current user namespace, so share the
			// host's /sys instead.
			opts = append(opts, oci.WithoutMounts("/sys"), oci.WithMounts([]specs.Mount{{
				Destination: "/sys",
				Type:        "bind",
				Source:      "/sys",
				Options:     []string{"rbind", "nosuid", "noexec", "nodev", "ro"},
			}}))
		}
	case hc.NetworkMode.IsContainer():
		// Resolved at start time by joining the other container's namespace.
	}
	if hc.PidMode.IsHost() {
		opts = append(opts, oci.WithHostNamespace(specs.PIDNamespace))
	}
	if hc.IpcMode.IsHost() {
		opts = append(opts, oci.WithHostNamespace(specs.IPCNamespace), oci.WithoutMounts("/dev/shm"))
	}
	if hc.UTSMode.IsHost() {
		opts = append(opts, oci.WithHostNamespace(specs.UTSNamespace))
	}
	if hc.CgroupnsMode.IsPrivate() || (hc.CgroupnsMode == "" && isCgroup2()) {
		opts = append(opts, oci.WithLinuxNamespace(specs.LinuxNamespace{Type: specs.CgroupNamespace}))
	}

	// Cgroups. In rootless mode a cgroup can only be created when the
	// current cgroup is delegated to the user (cgroup v2 with, for
	// example, a systemd user session). Otherwise cgroups are disabled,
	// which means resource limits cannot be enforced.
	if e.cfg.rootless {
		opts = append(opts, oci.WithCgroup(rootlessCgroupPath(in.id)))
	}
	return opts
}

// securityOpts returns the spec options for the container's privileges,
// capabilities, seccomp and AppArmor confinement and devices.
//
//nolint:gocyclo // one branch per security option Docker exposes
func securityOpts(cfg *config, hc *container.HostConfig) ([]oci.SpecOpts, error) {
	var opts []oci.SpecOpts
	seccompProfile := ""
	apparmorProfile := ""
	noNewPrivileges := false
	for _, so := range hc.SecurityOpt {
		k, v, _ := strings.Cut(so, "=")
		if k2, v2, ok := strings.Cut(so, ":"); ok && v == "" {
			k, v = k2, v2
		}
		switch k {
		case "seccomp":
			seccompProfile = v
		case "apparmor":
			apparmorProfile = v
		case "no-new-privileges":
			noNewPrivileges = v == "" || v == "true"
		case "label":
			// SELinux labels are not supported; ignore.
		default:
			return nil, fmt.Errorf("unsupported security option %q: %w", so, cerrdefs.ErrInvalidArgument)
		}
	}
	if hc.Privileged {
		opts = append(opts, oci.WithPrivileged, oci.WithAllDevicesAllowed, oci.WithHostDevices, oci.WithWriteableSysfs, oci.WithWriteableCgroupfs, oci.WithNewPrivileges)
	} else {
		opts = append(opts, oci.WithNewPrivileges)
		switch seccompProfile {
		case "unconfined":
			opts = append(opts, oci.WithSeccompUnconfined)
		case "", "builtin", "default":
			if !cfg.rootless {
				opts = append(opts, seccomp.WithDefaultProfile())
			}
		default:
			opts = append(opts, seccomp.WithProfile(seccompProfile))
		}
		if len(hc.CapAdd) > 0 {
			if containsAll(hc.CapAdd) {
				opts = append(opts, oci.WithAllKnownCapabilities)
			} else {
				opts = append(opts, oci.WithAddedCapabilities(normalizeCaps(hc.CapAdd)))
			}
		}
		if len(hc.CapDrop) > 0 {
			if containsAll(hc.CapDrop) {
				opts = append(opts, oci.WithCapabilities(nil))
			} else {
				opts = append(opts, oci.WithDroppedCapabilities(normalizeCaps(hc.CapDrop)))
			}
		}
		for _, d := range hc.Devices {
			perms := d.CgroupPermissions
			if perms == "" {
				perms = "rwm"
			}
			opts = append(opts, oci.WithDevices(d.PathOnHost, d.PathInContainer, perms))
		}
	}
	if apparmorProfile != "" && apparmorProfile != "unconfined" {
		opts = append(opts, oci.WithApparmorProfile(apparmorProfile))
	}
	if noNewPrivileges {
		opts = append(opts, oci.WithNoNewPrivileges)
	}
	if hc.ReadonlyRootfs {
		opts = append(opts, oci.WithRootFSReadonly())
	}
	if len(hc.MaskedPaths) > 0 {
		opts = append(opts, oci.WithMaskedPaths(hc.MaskedPaths))
	}
	if len(hc.ReadonlyPaths) > 0 {
		opts = append(opts, oci.WithReadonlyPaths(hc.ReadonlyPaths))
	}
	return opts, nil
}

// resourceOpts returns the spec options applying the container's resource
// limits.
func resourceOpts(hc *container.HostConfig) []oci.SpecOpts {
	var opts []oci.SpecOpts
	if hc.Memory > 0 {
		opts = append(opts, oci.WithMemoryLimit(uint64(hc.Memory)))
	}
	if hc.MemorySwap != 0 {
		opts = append(opts, oci.WithMemorySwap(hc.MemorySwap))
	}
	if hc.CPUShares > 0 {
		opts = append(opts, oci.WithCPUShares(uint64(hc.CPUShares)))
	}
	if hc.CpusetCpus != "" {
		opts = append(opts, oci.WithCPUs(hc.CpusetCpus))
	}
	if hc.CpusetMems != "" {
		opts = append(opts, oci.WithCPUsMems(hc.CpusetMems))
	}
	switch {
	case hc.NanoCPUs > 0:
		const period = 100000
		opts = append(opts, oci.WithCPUCFS(hc.NanoCPUs*period/1e9, period))
	case hc.CPUQuota > 0 || hc.CPUPeriod > 0:
		period := uint64(hc.CPUPeriod)
		if period == 0 {
			period = 100000
		}
		opts = append(opts, oci.WithCPUCFS(hc.CPUQuota, period))
	}
	if hc.PidsLimit != nil && *hc.PidsLimit > 0 {
		opts = append(opts, oci.WithPidsLimit(*hc.PidsLimit))
	}
	for _, u := range hc.Ulimits {
		if u == nil {
			continue
		}
		opts = append(opts, oci.WithRlimit(&specs.POSIXRlimit{
			Type: "RLIMIT_" + strings.ToUpper(u.Name),
			Hard: uint64(u.Hard),
			Soft: uint64(u.Soft),
		}))
	}
	if len(hc.Sysctls) > 0 {
		opts = append(opts, withSysctls(hc.Sysctls))
	}
	if hc.OomScoreAdj != 0 {
		opts = append(opts, withOOMScoreAdj(hc.OomScoreAdj))
	}
	return opts
}

// rootlessCgroupPath returns the cgroup to use for a container in rootless
// mode.
//
// Cgroup v2 forbids processes in inner nodes of the hierarchy, so a child of
// the current cgroup cannot be used. Instead the container is placed in a
// transient unit of the user's systemd instance (as the systemd cgroup
// driver of the runtime does), which owns the delegated subtree. Without a
// systemd user session there is no way to get a delegated cgroup, and the
// empty path disables cgroups for the container: it still runs, but
// resource limits are not enforced.
func rootlessCgroupPath(id string) string {
	if !isCgroup2() || !hasSystemdUserSession() {
		return ""
	}
	return "user.slice:docker:" + shortID(id)
}

// hasSystemdUserSession reports whether the user's systemd instance can be
// reached to create transient units.
func hasSystemdUserSession() bool {
	if addr := os.Getenv("DBUS_SESSION_BUS_ADDRESS"); addr != "" {
		return true
	}
	path := filepath.Join(runtimeDir(), "bus")
	if _, err := os.Stat(path); err == nil {
		_ = os.Setenv("DBUS_SESSION_BUS_ADDRESS", "unix:path="+path)
		return true
	}
	return false
}

func withSysctls(sysctls map[string]string) oci.SpecOpts {
	return func(_ context.Context, _ oci.Client, _ *containers.Container, s *oci.Spec) error {
		if s.Linux == nil {
			s.Linux = &specs.Linux{}
		}
		if s.Linux.Sysctl == nil {
			s.Linux.Sysctl = map[string]string{}
		}
		for k, v := range sysctls {
			s.Linux.Sysctl[k] = v
		}
		return nil
	}
}

func withOOMScoreAdj(adj int) oci.SpecOpts {
	return func(_ context.Context, _ oci.Client, _ *containers.Container, s *oci.Spec) error {
		if s.Process == nil {
			s.Process = &specs.Process{}
		}
		s.Process.OOMScoreAdj = &adj
		return nil
	}
}

func containsAll(caps []string) bool {
	for _, c := range caps {
		if strings.EqualFold(c, "ALL") {
			return true
		}
	}
	return false
}

func normalizeCaps(caps []string) []string {
	out := make([]string, 0, len(caps))
	for _, c := range caps {
		c = strings.ToUpper(c)
		if !strings.HasPrefix(c, "CAP_") {
			c = "CAP_" + c
		}
		out = append(out, c)
	}
	return out
}

// stopSignal returns the signal used by "docker stop" for the container.
func stopSignal(m *containerMeta) string {
	if m.Config != nil && m.Config.StopSignal != "" {
		return m.Config.StopSignal
	}
	return "SIGTERM"
}

// stopTimeout returns the time to wait before killing the container.
func stopTimeout(m *containerMeta, override *int) int {
	if override != nil {
		return *override
	}
	if m.Config != nil && m.Config.StopTimeout != nil {
		return *m.Config.StopTimeout
	}
	return 10
}

// parseSignal converts a Docker signal name or number to a signal number.
func parseSignal(sig string) (int, error) {
	if sig == "" {
		return 15, nil
	}
	if n, err := strconv.Atoi(sig); err == nil {
		return n, nil
	}
	name := strings.ToUpper(sig)
	if !strings.HasPrefix(name, "SIG") {
		name = "SIG" + name
	}
	if n, ok := signalMap[name]; ok {
		return n, nil
	}
	return 0, fmt.Errorf("invalid signal %q: %w", sig, cerrdefs.ErrInvalidArgument)
}

var signalMap = map[string]int{
	"SIGHUP": 1, "SIGINT": 2, "SIGQUIT": 3, "SIGILL": 4, "SIGTRAP": 5, "SIGABRT": 6, "SIGBUS": 7,
	"SIGFPE": 8, "SIGKILL": 9, "SIGUSR1": 10, "SIGSEGV": 11, "SIGUSR2": 12, "SIGPIPE": 13,
	"SIGALRM": 14, "SIGTERM": 15, "SIGSTKFLT": 16, "SIGCHLD": 17, "SIGCONT": 18, "SIGSTOP": 19,
	"SIGTSTP": 20, "SIGTTIN": 21, "SIGTTOU": 22, "SIGURG": 23, "SIGXCPU": 24, "SIGXFSZ": 25,
	"SIGVTALRM": 26, "SIGPROF": 27, "SIGWINCH": 28, "SIGIO": 29, "SIGPWR": 30, "SIGSYS": 31,
	"SIGRTMIN": 34, "SIGRTMAX": 64,
}

// isHostConfigNetworkContainer is a small helper for readability.
func networkModeName(hc *container.HostConfig) string {
	if hc == nil || hc.NetworkMode == "" || hc.NetworkMode.IsDefault() {
		return "bridge"
	}
	return string(hc.NetworkMode)
}
