FROM docker:test-dind
COPY ./ssh-withpassword/entrypoint.sh /
RUN chmod +x /entrypoint.sh
RUN apk --no-cache add shadow openssh-server && \
  groupadd -f docker && \
  useradd -m penguin && \
  usermod -aG docker penguin && \
  echo penguin:mmNNTTbb140821 | chpasswd && \
  chsh -s /bin/sh penguin && \
  ssh-keygen -A
# workaround: ssh session excludes /usr/local/bin from $PATH
RUN ln -s /usr/local/bin/docker /usr/bin/docker
EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]
# usage: docker run --privileged -p 22 $THIS_IMAGE
