services:
  engine:
      build:
        context: ./testdata
        dockerfile: Dockerfile.connhelper-ssh
        args: 
          - ENGINE_VERSION
      environment:
        - TEST_CONNHELPER_SSH_ID_RSA_PUB
