services:

  registry:
    image: 'registry:2'

  engine:
      image: 'docker:${ENGINE_VERSION:-25.0}-dind'
      privileged: true
      command: ['--insecure-registry=registry:5000']
      environment:
        - DOCKER_TLS_CERTDIR=

  notary-server:
      build:
        context: ./testdata
        dockerfile: Dockerfile.notary-server
      ports:
        - 4443:4443
      command: ['notary-server', '-config=/fixtures/notary-config.json']

  evil-notary-server:
      build:
        context: ./testdata
        dockerfile: Dockerfile.evil-notary-server
      ports:
        - 4444:4443
      command: ['notary-server', '-config=/fixtures/notary-config.json']
