FROM    golang:1.12.1 as build
ARG     GOLANGCI_LINTER_SHA=v1.16.0

ENV     CGO_ENABLED=0
RUN     GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@$GOLANGCI_LINTER_SHA

FROM golang:1.12.1-alpine as lint

COPY --from=build /go/bin/golangci-lint /usr/local/bin
WORKDIR /go/src/github.com/docker/cli
ENV     DISABLE_WARN_OUTSIDE_CONTAINER=1
ENV     CGO_ENABLED=0
ENTRYPOINT ["/usr/local/bin/golangci-lint"]
CMD     ["run", "--config=.golangci.yml"]
COPY    . .
