# syntax=docker/dockerfile:1.3

FROM koalaman/shellcheck-alpine:v0.7.1 AS shellcheck
WORKDIR /src
RUN --mount=type=bind,target=. \
  set -eo pipefail; \
  find scripts/ contrib/completion/bash -type f | grep -v scripts/winresources | grep -v '.*.ps1' | xargs shellcheck
