#!/usr/bin/env bash

set -eu

usage() {
  echo "usage: ./scripts/vendor <init|update|validate|outdated|clean> [-c]"
  echo
  echo "options:"
  echo "  c  remove dummy go.mod after command execution"
  exit 1
}

init() {
  # create dummy go.mod, see comment in vendor.mod
  cat > go.mod <<EOL
module github.com/docker/cli

go 1.17
EOL
}

update() {
  (set -x ; go mod tidy -compat=1.17 -modfile=vendor.mod; go mod vendor -modfile=vendor.mod)
}

validate() {
  diff=$(git status --porcelain -- vendor.mod vendor.sum vendor)
  if [ -n "$diff" ]; then
    echo >&2 'ERROR: Vendor result differs. Please vendor your package with "make -f docker.Makefile vendor"'
    echo "$diff"
    exit 1
  fi
}

outdated() {
  if [ ! -x "$(command -v go-mod-outdated)" ]; then
    echo "go-mod-outdated not found. Install with 'go install github.com/psampaz/go-mod-outdated@v0.8.0'"
    exit 1
  fi
  (set -x ; go list -mod=vendor -mod=readonly -modfile=vendor.mod -u -m -json all | go-mod-outdated -update -direct)
}

clean() {
  echo "Remove dummy go.mod file"
  rm go.mod
}

command="${1:-"usage"}"
if [ $# -gt 1 ]; then
  shift # Remove command from the argument list
fi

case $command in
  "init")
    init
    exit 0
    ;;
  "update")
    init
    update
    ;;
  "validate")
    init
    update
    validate
    ;;
  "outdated")
    init
    outdated
    ;;
  "clean")
    clean
    exit 0
    ;;
  *)
    usage
    ;;
esac

while getopts ":c" opt; do
  case $opt in
    c)
      clean
      ;;
    *)
      ;;
  esac
done
