#!/usr/bin/env bash
set -eu -o pipefail

src=busybox@sha256:3e8fa85ddfef1af9ca85a5cfb714148956984e02f00bec3f7f49d3925a91e0e7
dest=registry:5000/busybox:1.27.2
docker pull $src
docker tag $src $dest
# ensure busybox:latest is defined as kubernetes e2e uses it to setup the cluster
docker tag $src busybox:latest
docker push $dest
